import Head from "next/head";
import { AppLayout } from "src/layouts/AppLayout";
import { useCounter } from "src/hooks/useCounter";
import { useInputArray } from "src/hooks/useInputArray";
import "src/styles/globals.css";
import { fetcher } from "src/utils/fetcher";
import { SWRConfig } from "swr";

const MyApp = ({ Component, pageProps }) => {
  const counter = useCounter();
  const inputArray = useInputArray();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{ fetcher: fetcher }}>
        <AppLayout>
          <Component {...pageProps} {...counter} {...inputArray} />
        </AppLayout>
      </SWRConfig>
    </>
  );
};

export default MyApp;
